# File: railway.toml (Versi Lengkap & Final)

[nix]
providers = ["java"]

[phases.setup]
nixpkgs.jdk = "jdk21"

# TAMBAHKAN BAGIAN INI UNTUK MEMAKSA PERINTAH BUILD
[phases.build]
cmds = ["mvn clean package -DskipTests"]